server:
    port: 8084
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/user_db?autoReconnect=true&useSSL=false
    username: user2
    password: password
    driver-class-name: com.mysql.jdbc.Driver