DROP DATABASE IF EXISTS user_db;
DROP USER IF EXISTS `user`@`%`;
CREATE DATABASE IF NOT EXISTS user_db;
CREATE USER IF NOT EXISTS `user`@`%` IDENTIFIED BY 'password';
GRANT ALL ON user_db.* TO `user`@`%`;